### ISSUE TITLE
TODO before fMRI

### ISSUE THREAD

**Issue by aforren1** [aforren1/Psychoobox#11]
- [x] Rectangles (either as textures or not)
- [x] Images
- [x] Audio (remapping from old-style code, refactor (e.g. Add('buffer' or 'slave', ...)))
- [ ] ~~Serial (just remapping from old-style code)~~ secondary
- [ ] Parallel(?) What platform?
- [x] text
