### ISSUE TITLE
Feature checklist

### ISSUE THREAD

**Issue by aforren1** [aforren1/Psychoobox#2]
Window:
- [x] Open
  - [x] Offscreen
- [x] Close
  - [x] Close specific
- [x] MakeTexture
- [ ] PanelFitter
- [ ] AsyncFlip Begin/End/CheckEnd/WaitUntilCertain

Shapes:
- [ ] SelectStereoDrawBuffer
- [x] Line
- [x] Arc (frame + fill)
- [x] Rect (frame + fill)
  - [ ] See `help PsychRects`
- [x] Oval (frame + fill)
- [x] Poly (frame + fill)

OpenGL functions:
- [x] ~~glPoint~~ moot, just using DrawDots instead 
- [ ] gluDisk
- [x] DrawDots
- [x] DrawLines
- [x] ~~BlendFunction~~ best left alone

Text:
- [x] ~~TextMode(s)~~ OSX only, so ignoring
- [x] TextSize
- [x] TextStyle
- [x] TextFont
- [ ] TextBounds
- [x] DrawText 
  - [x] Formatted
- [x] TextColor
- [x] TextBackgroundColor
- [x] TextTransform

Images:
- [ ] PreloadTextures
- [x] DrawTexture(s)
- [ ] CopyWindow

Movies:
- [ ] OpenMovie
- [ ] CloseMovie
- [ ] GetMovieImage
- [ ] PlayMovie
- [ ] Set/Get MovieTimeIndex
- [ ] CreateMovie
- [ ] FinalizeMovie
- [ ] AddFrameToMovie
- [ ] AddAudioBufferToMovie

Video Capture:
- [ ] VideoCaptureDevices
- [ ] Open/Close/Start/Stop VideoCapture
- [ ] GetCapturedImage
- [ ] SetVideoCaptureParameter

Various external OpenGL:

...

PsychPortAudio:
- [x] Open/Close (+ slave)
- [x] FillBuffer
- [x] CreateBuffer
- [x] DeleteBuffer
- [ ] RefillBuffer
- [ ] SetLoop
- [x] Start/Stop
- [ ] RescheduleStart
- [x] GetStatus
- [ ] GetAudioData

IOPort:
- [ ] Close
- [ ] Write
- [ ] Flush
- [ ] Read
- [ ] BytesAvailable

Serial Specific:
- [ ] OpenSerialPort
- [ ] ConfigureSerialPort

...
